include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_const_constructors: true
    unnecessary_this: true
    prefer_final_fields: true
    avoid_print: true