name: uber_copilot
description: AI-powered co-pilot app for Uber earners - Hackathon Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Navigation
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # UI Components
  fl_chart: ^0.65.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1

  # Routing
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true